[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "groovn"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "duckdb",
    "pandas",
    "pyarrow",
    "matplotlib",
    "seaborn",
    "jupyterlab",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["scripts", "notebooks"]
testpaths = ["tests"]
